// flow-typed signature: 4733fbff91a6394d86bf6afe6b930f48
// flow-typed version: <<STUB>>/babel-plugin-encapsulate-jsx_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-encapsulate-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-encapsulate-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-encapsulate-jsx/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-encapsulate-jsx/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-encapsulate-jsx/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-encapsulate-jsx/dist/index'>;
}
declare module 'babel-plugin-encapsulate-jsx/index' {
  declare module.exports: $Exports<'babel-plugin-encapsulate-jsx'>;
}
declare module 'babel-plugin-encapsulate-jsx/index.js' {
  declare module.exports: $Exports<'babel-plugin-encapsulate-jsx'>;
}
declare module 'babel-plugin-encapsulate-jsx/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-encapsulate-jsx/test/test'>;
}
