// flow-typed signature: 7eda57fbfb347b66e6ece753aa2efbb7
// flow-typed version: <<STUB>>/babel-plugin-jsx-display-if_v^3.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-jsx-display-if'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-jsx-display-if' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-jsx-display-if/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-jsx-display-if/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-jsx-display-if/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-display-if/dist/index'>;
}
declare module 'babel-plugin-jsx-display-if/index' {
  declare module.exports: $Exports<'babel-plugin-jsx-display-if'>;
}
declare module 'babel-plugin-jsx-display-if/index.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-display-if'>;
}
declare module 'babel-plugin-jsx-display-if/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-jsx-display-if/test/test'>;
}
