// flow-typed signature: 75cef3b9aec9bf41f0d46f75d5dc7e35
// flow-typed version: <<STUB>>/encapsulate-css_v^1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'encapsulate-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'encapsulate-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'encapsulate-css/dist/index' {
  declare module.exports: any;
}

declare module 'encapsulate-css/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'encapsulate-css/dist/index.js' {
  declare module.exports: $Exports<'encapsulate-css/dist/index'>;
}
declare module 'encapsulate-css/index' {
  declare module.exports: $Exports<'encapsulate-css'>;
}
declare module 'encapsulate-css/index.js' {
  declare module.exports: $Exports<'encapsulate-css'>;
}
declare module 'encapsulate-css/test/test.js' {
  declare module.exports: $Exports<'encapsulate-css/test/test'>;
}
