// flow-typed signature: 3b53449ef072b1105442414e7f01d9ae
// flow-typed version: <<STUB>>/react-scrollspy_v^3.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrollspy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrollspy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrollspy/lib/Scrollspy' {
  declare module.exports: any;
}

declare module 'react-scrollspy/lib/throttle' {
  declare module.exports: any;
}

declare module 'react-scrollspy/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrollspy/lib/Scrollspy.js' {
  declare module.exports: $Exports<'react-scrollspy/lib/Scrollspy'>;
}
declare module 'react-scrollspy/lib/throttle.js' {
  declare module.exports: $Exports<'react-scrollspy/lib/throttle'>;
}
declare module 'react-scrollspy/webpack.config.babel.js' {
  declare module.exports: $Exports<'react-scrollspy/webpack.config.babel'>;
}
