// flow-typed signature: 3ce9ba801aef788070ee0de4e946c7bc
// flow-typed version: <<STUB>>/react-onclickoutside_v^6.4.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickoutside/es/generateOutsideCheck' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/es/index' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/lib/generateOutsideCheck' {
  declare module.exports: any;
}

declare module 'react-onclickoutside/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onclickoutside/es/generateOutsideCheck.js' {
  declare module.exports: $Exports<'react-onclickoutside/es/generateOutsideCheck'>;
}
declare module 'react-onclickoutside/es/index.js' {
  declare module.exports: $Exports<'react-onclickoutside/es/index'>;
}
declare module 'react-onclickoutside/lib/generateOutsideCheck.js' {
  declare module.exports: $Exports<'react-onclickoutside/lib/generateOutsideCheck'>;
}
declare module 'react-onclickoutside/lib/index.js' {
  declare module.exports: $Exports<'react-onclickoutside/lib/index'>;
}
